name: Test with KICS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  kics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      
      - name: KICS Github Action
        uses: Checkmarx/kics-github-action@v2
        with:
    # path to file or directory to scan
          path: ./
    


